apiVersion: v1
kind: PersistentVolume
metadata:
  name: homarr-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  hostPath:
    path: /var/lib/homarr/appdata
  claimRef:
    name: homarr-pvc
    namespace: homarr
