apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /var/lib/jellyfin/appdata
  claimRef:
    name: jellyfin-pvc
    namespace: jellyfin
