apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: Firefly
  name: firefly
  namespace: firefly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Firefly
  template:
    metadata:
      labels:
        app: Firefly
    spec:
      volumes:
      - name: firefly-pv
        persistentVolumeClaim:
          claimName: firefly-pvc
      initContainers:
        - name: init-storage
          image: busybox
          command:
            - sh
            - -c
            - |
              mkdir -p /storage/database \
                        /storage/logs \
                        /storage/app/public \
                        /storage/framework/cache \
                        /storage/framework/sessions \
                        /storage/framework/views && \
              chown -R 33:33 /storage
          volumeMounts:
            - name: firefly-pv
              mountPath: /storage
      containers:
        - image: fireflyiii/core:latest
          name: fireflyi
          envFrom:
            - secretRef:
                name: firefly-secret
          volumeMounts:
            - name: firefly-pv
              mountPath: /var/www/html/storage
