apiVersion: v1
kind: PersistentVolume
metadata:
  name: firelfly-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/firefly
  claimRef:
    name: firefly-pvc
    namespace: firefly
