apiVersion: v1
kind: Namespace
metadata:
  name: n8n
---
apiVersion: v1
kind: Secret
metadata:
  name: n8n-basic-auth
  namespace: n8n
type: Opaque
stringData:
  password: "change-me"  # TODO: change this
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
  namespace: n8n
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # adjust if you want
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
        - name: n8n
          image: docker.n8n.io/n8nio/n8n:latest
          imagePullPolicy: IfNotPresent
          env:
            # DB: SQLite (default) with persistent volume
            - name: DB_TYPE
              value: "sqlite"

            # Basic auth for UI
            - name: N8N_BASIC_AUTH_ACTIVE
              value: "true"
            - name: N8N_BASIC_AUTH_USER
              value: "admin"
            - name: N8N_BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-basic-auth
                  key: password

            # Optional but good defaults for later (Ingress etc.)
            - name: N8N_PORT
              value: "5678"
          ports:
            - containerPort: 5678
          volumeMounts:
            - name: n8n-data
              mountPath: /home/node/.n8n
      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: n8n-data
---
apiVersion: v1
kind: Service
metadata:
  name: n8n
  namespace: n8n
spec:
  selector:
    app: n8n
  ports:
    - port: 5678
      targetPort: 5678
      protocol: TCP
  type: ClusterIP

