apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-wger-pvc
  namespace: wger
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
