apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfinn-pvc
  namespace: jellyfinn
spec:
  storageClassName: ""
  volumeName: jellyfinn-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

