apiVersion: v1
kind: Pod
metadata:
  labels:
    run: whoami
  name: whoami
  namespace: basics
spec:
  containers:
  - args:
    - whoami
    image: traefik/whoami
    name: pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
