apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-pvc
  namespace: firefly
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
